# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-24 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0002_auto_20170808_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Feed.Profile'),
        ),
    ]
