# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0003_auto_20171023_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='post',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set([('profile', 'order')]),
        ),
    ]
