# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 04:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0004_auto_20171026_2232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='post',
            name='order',
        ),
    ]
